autoInstallPeers: false
catalogMode: prefer
cleanupUnusedCatalogs: true
dangerouslyAllowAllBuilds: false
dedupePeers: true
enablePrePostScripts: false
engineStrict: true
hoist: false
hoistPattern: []
hoistWorkspacePackages: false
ignoreScripts: true
minimumReleaseAge: 10080
minimumReleaseAgeIgnoreMissingTime: true
minimumReleaseAgeStrict: true
packages:
  - meta/*
  - hello-world
  - my-app
  - learning
publicHoistPattern:
  - tslib
  - "@typescript/native-preview"
  - "@typescript"
  - tsx
  - "*oxlint*"
  - "*oxfmt*"
savePrefix: ^
shamefullyHoist: false
strictPeerDependencies: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 129600
verifyDepsBeforeRun: warn
catalog:
  '@types/express': ^5.0.6
  '@types/node': ^25.9.1
  body-parser: ^2.2.2
  express: ^5
  jose: ^6.2.3
  morgan: ~1.9.1
  serve-static: ^2.2.1
